language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm

install:
  - composer install

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
