language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: hhvm

install:
  - composer install

script: sh -c "if [ \"$TRAVIS_PHP_VERSION\" = '5.5' ]; then ./vendor/bin/phpunit --coverage-clover=coverage.clover; else ./vendor/bin/phpunit; fi"

after_script:
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" = '5.5' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" = '5.5' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi"
